// ABOUTME: Defines the authored /play world layout, route graph, zones, and gameplay checkpoints.
// ABOUTME: Gate 2R keeps this data foundation-only so later art passes start from clean geometry.

export const WORLD_HALF_SIZE = 190;
export const MAP_PADDING = 24;
export const ISLAND_RADIUS = 158;
export const WATER_RADIUS = ISLAND_RADIUS + 42;
export const SECURITY_SCAN_OFFSET = [0, 18];
export const SECURITY_SCAN_ROTATION = -2.11;

export const roadSurfaceProfiles = {
  avenue: {
    label: 'Main Avenue',
    grip: 1.04,
    drag: 0.985,
    smoke: '#dce7df',
    skid: '#16241f',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  street: {
    label: 'District Street',
    grip: 1.0,
    drag: 0.975,
    smoke: '#d4ddd3',
    skid: '#1f2a24',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  plaza: {
    label: 'Plaza Stone',
    grip: 0.96,
    drag: 0.96,
    smoke: '#ded7c8',
    skid: '#373126',
    audio: 'stone',
    particle: 'stone-chip',
  },
  security: {
    label: 'Security Resin',
    grip: 1.08,
    drag: 0.98,
    smoke: '#9ee8ff',
    skid: '#07394a',
    audio: 'synth-asphalt',
    particle: 'scan-sparks',
  },
  stunt: {
    label: 'Stunt Rubber',
    grip: 1.14,
    drag: 0.97,
    smoke: '#ffd9a8',
    skid: '#42231b',
    audio: 'rubber',
    particle: 'rubber-fleck',
  },
  dirt: {
    label: 'Packed Dirt',
    grip: 0.74,
    drag: 0.9,
    smoke: '#c4a077',
    skid: '#6f4b2e',
    audio: 'dirt',
    particle: 'dust-heavy',
  },
  bridge: {
    label: 'Pier Deck',
    grip: 0.9,
    drag: 0.94,
    smoke: '#c6d4dd',
    skid: '#2d3f47',
    audio: 'wood',
    particle: 'splinter',
  },
};

export const districtFootprints = [
  { id: 'launch-harbor', label: 'Launch Harbor', center: [32, -112], size: [34, 26], color: '#7cffb2', kind: 'plaza' },
  { id: 'fcc-campus', label: 'FCC Campus Grove', center: [-84, 88], size: [68, 44], color: '#9ccfff', kind: 'campus' },
  { id: 'security-yard', label: 'Security Yard', center: [-102, -42], size: [38, 32], color: '#68d8ff', kind: 'security' },
  { id: 'gallery-yard', label: 'Gallery Yard', center: [72, 64], size: [38, 30], color: '#ffcc66', kind: 'workshop' },
  { id: 'north-ridge', label: 'North Ridge', center: [22, 116], size: [52, 28], color: '#ff6d8d', kind: 'tower' },
  { id: 'west-services', label: 'West Services', center: [-88, -92], size: [52, 34], color: '#92ffea', kind: 'trail' },
  { id: 'south-run', label: 'South Run', center: [20, -104], size: [62, 34], color: '#e6f3ff', kind: 'driving' },
  { id: 'stunt-yard', label: 'Stunt Foundation', center: [88, -72], size: [46, 34], color: '#ff9b6d', kind: 'driving' },
  { id: 'east-harbor', label: 'Signal Harbor', center: [118, 52], size: [40, 34], color: '#78b7ff', kind: 'harbor' },
  { id: 'west-pier', label: 'Data Pier', center: [-112, 50], size: [26, 24], color: '#79ffc5', kind: 'pier' },
];

export const terrainBrushes = [];
export const meadowDetailPatches = [];
export const districtSurfaceBreakups = [];
export const fieldMotifClusters = [];
export const canalSegments = [];

export const scenicPropZones = [
  { id: 'launch-foundation', center: [32, -112], radius: 26, density: 0.3, palette: 'start' },
  { id: 'fcc-foundation', center: [-104, 82], radius: 30, density: 0.3, palette: 'campus' },
  { id: 'security-foundation', center: [-118, -18], radius: 27, density: 0.3, palette: 'security' },
  { id: 'stunt-foundation', center: [88, -72], radius: 28, density: 0.25, palette: 'stunt' },
];

export const roadPaths = [
  {
    id: 'coastal-loop',
    label: 'Coastal Loop',
    hierarchy: 'avenue',
    closed: true,
    width: 5.0,
    shoulder: 2.2,
    color: '#24342c',
    points: [
      [-115, -57],
      [-89, -114],
      [-28, -141],
      [46, -136],
      [99, -85],
      [131, -28],
      [138, 42],
      [91, 101],
      [28, 140],
      [-48, 132],
      [-112, 88],
      [-122, 18],
    ],
  },
  {
    id: 'launch-spine',
    label: 'Launch Spine',
    hierarchy: 'avenue',
    width: 4.7,
    shoulder: 2.4,
    color: '#22352f',
    points: [
      [58, -118],
      [36, -88],
      [10, -56],
      [-12, -24],
      [-38, 8],
      [-70, 40],
      [-96, 78],
    ],
  },
  {
    id: 'campus-way',
    label: 'Campus Way',
    hierarchy: 'plaza',
    width: 4.2,
    shoulder: 2,
    color: '#2f3f38',
    points: [
      [-96, 78],
      [-82, 100],
      [-48, 132],
    ],
  },
  {
    id: 'security-cut',
    label: 'Security Cut',
    hierarchy: 'security',
    width: 4.5,
    shoulder: 2,
    color: '#163a42',
    points: [
      [-38, 8],
      [-68, -6],
      [-98, -24],
      [-126, -56],
    ],
  },
  {
    id: 'gallery-spine',
    label: 'Gallery Spine',
    hierarchy: 'street',
    width: 4.3,
    shoulder: 2,
    color: '#2d382d',
    points: [
      [-12, -24],
      [24, 8],
      [64, 30],
      [96, 54],
      [120, 78],
    ],
  },
  {
    id: 'project-yard-road',
    label: 'Project Yard Road',
    hierarchy: 'street',
    width: 4.2,
    shoulder: 1.9,
    color: '#303b30',
    points: [
      [64, 30],
      [70, 64],
      [48, 96],
      [28, 140],
    ],
  },
  {
    id: 'career-link',
    label: 'Career Link',
    hierarchy: 'street',
    width: 4.2,
    shoulder: 1.8,
    color: '#29382f',
    points: [
      [24, 8],
      [62, -18],
      [98, -38],
      [131, -28],
    ],
  },
  {
    id: 'cv-run',
    label: 'CV Run',
    hierarchy: 'plaza',
    width: 4.1,
    shoulder: 1.9,
    color: '#35382f',
    points: [
      [10, -56],
      [12, -84],
      [24, -118],
      [-28, -141],
    ],
  },
  {
    id: 'farm-track',
    label: 'Farm Track',
    hierarchy: 'dirt',
    width: 3.9,
    shoulder: 1.7,
    color: '#7a5a37',
    points: [
      [-126, -56],
      [-106, -92],
      [-76, -122],
      [-28, -141],
    ],
  },
  {
    id: 'stunt-run',
    label: 'Stunt Run',
    hierarchy: 'stunt',
    width: 4.4,
    shoulder: 1.8,
    color: '#3c2722',
    points: [
      [99, -85],
      [88, -72],
      [74, -52],
      [98, -38],
    ],
  },
  {
    id: 'harbor-link',
    label: 'Harbor Link',
    hierarchy: 'bridge',
    width: 3.8,
    shoulder: 1.5,
    color: '#33464c',
    points: [
      [96, 54],
      [120, 78],
      [138, 42],
    ],
  },
  {
    id: 'data-pier',
    label: 'Data Pier',
    hierarchy: 'bridge',
    width: 3.6,
    shoulder: 1.4,
    color: '#32464b',
    points: [
      [-112, 88],
      [-132, 66],
      [-122, 18],
    ],
  },
  {
    id: 'todo-link',
    label: 'Todo Link',
    hierarchy: 'plaza',
    width: 3.8,
    shoulder: 1.7,
    color: '#343930',
    points: [
      [-70, 40],
      [-82, 16],
      [-68, -6],
    ],
  },
  {
    id: 'archive-link',
    label: 'Archive Link',
    hierarchy: 'plaza',
    width: 3.8,
    shoulder: 1.6,
    color: '#333a30',
    points: [
      [-96, 78],
      [-72, 94],
      [-48, 110],
    ],
  },
];

export const routeThresholds = [
  { id: 'start-campus', label: 'Campus Route', position: [-78, 0.05, 52], rotation: -0.78, width: 18, color: '#9ccfff' },
  { id: 'campus-north', label: 'North Ridge', position: [-48, 0.05, 132], rotation: Math.PI / 2, width: 18, color: '#ff6d8d' },
  { id: 'start-security', label: 'Security Cut', position: [-68, 0.05, -6], rotation: -2.08, width: 18, color: '#68d8ff' },
  { id: 'gallery-gate', label: 'Gallery', position: [64, 0.05, 30], rotation: 0.98, width: 18, color: '#ffcc66' },
  { id: 'stunt-gate', label: 'Stunt', position: [88, 0.05, -72], rotation: 0.64, width: 18, color: '#ff9b6d' },
  { id: 'farm-gate', label: 'Farm Track', position: [-106, 0.05, -92], rotation: -2.68, width: 16, color: '#c4a077' },
];

export const roadSegments = roadPaths.flatMap((path) => pathToSegments(path));

function pathToSegments(path) {
  const segments = [];
  const limit = path.closed ? path.points.length : path.points.length - 1;
  for (let index = 0; index < limit; index += 1) {
    const a = path.points[index];
    const b = path.points[(index + 1) % path.points.length];
    const dx = b[0] - a[0];
    const dz = b[1] - a[1];
    const length = Math.hypot(dx, dz);
    segments.push([
      (a[0] + b[0]) / 2,
      (a[1] + b[1]) / 2,
      path.width,
      length + path.width * 0.64,
      Math.atan2(dx, dz),
    ]);
  }
  return segments;
}

export const boostPads = [
  {
    id: 'scanner-surge',
    label: 'Scanner Surge',
    position: [-72, 0, -8],
    rotation: -2.65,
    impulse: 22,
    lift: 0.1,
    color: '#6ce7ff',
    sound: 'boost-scan',
  },
  {
    id: 'document-dash',
    label: 'Document Dash',
    position: [12, 0, -84],
    rotation: 0.2,
    impulse: 20,
    lift: 0.12,
    color: '#fff2a8',
    sound: 'boost-paper',
  },
  {
    id: 'stunt-kicker',
    label: 'Stunt Kicker',
    position: [88, 0, -72],
    rotation: 1.0,
    impulse: 24,
    lift: 0.2,
    color: '#ff9b6d',
    sound: 'boost-stunt',
  },
];

export const worldZones = [
  {
    id: 'landing',
    name: 'Launch Plaza',
    kind: 'Home',
    title: 'Launch Harbor',
    districtId: 'launch-harbor',
    position: [30, 0, -104],
    rotation: -0.22,
    radius: 10,
    color: '#7cffb2',
    shape: 'hub',
    dialogueId: '0',
    achievement: 'first_stop',
    accent: '#7cffb2',
    summary: 'Start point for the portfolio drive.',
    actions: [
      { label: 'Main Portfolio', href: '../index.html' },
      { label: 'Projects', href: '../projects.html' },
    ],
  },
  {
    id: 'education',
    name: 'FCC Education Grove',
    kind: 'Academics',
    title: 'FCC Education Grove',
    districtId: 'fcc-campus',
    position: [-104, 0, 82],
    rotation: -0.08,
    radius: 11,
    color: '#9ccfff',
    shape: 'library',
    dialogueId: '6',
    achievement: 'education_library',
    accent: '#9ccfff',
    summary: 'Forman Christian College University S-block identity remains protected here.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'security',
    name: 'Security Lab Gate',
    kind: 'Offensive Security',
    title: 'Cyber Sentinel Lab',
    districtId: 'security-yard',
    position: [-98, 0, -42],
    rotation: -0.28,
    radius: 14,
    color: '#68d8ff',
    shape: 'lab',
    dialogueId: '1',
    achievement: 'security_lab',
    scanRequired: true,
    accent: '#68d8ff',
    summary: 'Security portfolio stop with scan interaction compatibility retained.',
    actions: [
      { label: 'CV', href: '../cv.html' },
      { label: 'Cyber Sentinel', href: '../cyber-sentinel.html' },
    ],
  },
  {
    id: 'projects',
    name: 'Projects Yard',
    kind: 'Project Gallery',
    title: 'Project Yard',
    districtId: 'gallery-yard',
    position: [84, 0, 72],
    rotation: -0.44,
    radius: 10,
    color: '#ffcc66',
    shape: 'foundry',
    achievement: 'projects_foundry',
    projectGallery: true,
    accent: '#ffcc66',
    summary: 'Project links stay available while the district waits for a later art pass.',
    actions: [{ label: 'Projects Page', href: '../projects.html' }],
  },
  {
    id: 'sentinel',
    name: 'Cyber Sentinel Ridge',
    kind: 'Final Year Project',
    title: 'Cyber Sentinel Ridge',
    districtId: 'north-ridge',
    position: [16, 0, 118],
    rotation: -0.12,
    radius: 11,
    color: '#ff6d8d',
    shape: 'tower',
    dialogueId: '3',
    achievement: 'cyber_sentinel',
    accent: '#ff6d8d',
    summary: 'Future ridge landmark for cybersecurity work.',
    actions: [{ label: 'Read Blog', href: '../cyber-sentinel.html' }],
  },
  {
    id: 'career',
    name: 'Career Signal Office',
    kind: 'Experience',
    title: 'Career Office',
    districtId: 'stunt-yard',
    position: [108, 0, -28],
    rotation: -0.24,
    radius: 10,
    color: '#b6a0ff',
    shape: 'office',
    dialogueId: '5',
    achievement: 'career_office',
    accent: '#7df0ff',
    summary: 'Career evidence stop with existing portfolio actions preserved.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'skills',
    name: 'Skills Terminal',
    kind: 'Stack',
    title: 'Skills Service Road',
    districtId: 'west-services',
    position: [-92, 0, -78],
    rotation: 0.24,
    radius: 10,
    color: '#92ffea',
    shape: 'terminal',
    dialogueId: '2',
    achievement: 'skills_terminal',
    accent: '#92ffea',
    summary: 'Technical skills stop on the west service foundation.',
    actions: [{ label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' }],
  },
  {
    id: 'awards',
    name: 'Archive Steps',
    kind: 'Certificates',
    title: 'Awards Archive',
    districtId: 'fcc-campus',
    position: [-54, 0, 86],
    rotation: -0.18,
    radius: 8,
    color: '#ffdf8a',
    shape: 'trophy',
    dialogueId: '7',
    achievement: 'awards_tower',
    accent: '#ffd166',
    summary: 'Awards stop near campus without adding decoration in Gate 2R.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'cv',
    name: 'CV Vault',
    kind: 'Resume',
    title: 'CV Vault',
    districtId: 'south-run',
    position: [2, 0, -82],
    rotation: 0.12,
    radius: 9,
    color: '#e6f3ff',
    shape: 'vault',
    achievement: 'cv_vault',
    accent: '#f7f5a8',
    summary: 'CV action remains reachable from the south run.',
    lines: [
      'Resume archive, project record, certificates, skills, awards, and downloadable PDFs.',
      'Open the document-first version for the full professional profile.',
    ],
    actions: [
      { label: 'Open CV Page', href: '../cv.html' },
      { label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' },
      { label: 'Cyber CV PDF', href: '../Abdullah-Mehtab-CV-Cyber-v2.pdf' },
    ],
  },
  {
    id: 'todo',
    name: 'Todo Board',
    kind: 'Blog / List',
    title: 'Todo Board',
    districtId: 'security-yard',
    position: [-92, 0, 18],
    rotation: 0.34,
    radius: 9,
    color: '#d8ff92',
    shape: 'board',
    achievement: 'todo_board',
    accent: '#fca5ff',
    summary: 'Existing todo page action remains compatible.',
    lines: [
      'The never-ending list keeps active tasks, experiments, reminders, and ideas visible.',
      'A lightweight log for work that is being tested, refined, or revisited.',
    ],
    actions: [{ label: 'Open Todo', href: '../todo.html' }],
  },
  {
    id: 'circuit',
    name: 'Circuit Gate',
    kind: 'Time Trial',
    title: 'Circuit Start',
    districtId: 'north-ridge',
    position: [48, 0, 96],
    rotation: -0.28,
    radius: 12,
    color: '#ff9b6d',
    shape: 'gate',
    achievement: 'circuit_gate',
    accent: '#ff9b6d',
    startsCircuit: true,
    summary: 'Circuit foundation stays testable, but final stunt art is deferred.',
    lines: [
      'This gate starts the island loop circuit.',
      'Follow the checkpoints around the coast and return clean.',
    ],
  },
  {
    id: 'contact',
    name: 'Signal Harbor',
    kind: 'Links',
    title: 'Signal Harbor',
    districtId: 'east-harbor',
    position: [118, 0, 48],
    rotation: -0.34,
    radius: 9,
    color: '#78b7ff',
    shape: 'post',
    dialogueId: '8',
    achievement: 'contact_port',
    accent: '#78b7ff',
    summary: 'Contact action remains available on the east harbor foundation.',
    actions: [
      { label: 'GitHub', href: 'https://github.com/Abdullah-Mehtab' },
      { label: 'LinkedIn', href: 'https://linkedin.com/in/abdullah-mehtab' },
      { label: 'Email', href: 'mailto:abdullahmehtab666@gmail.com' },
    ],
  },
  {
    id: 'behind',
    name: 'Behind The Build',
    kind: 'Stack',
    title: 'Behind The Build',
    districtId: 'south-run',
    position: [-26, 0, -104],
    rotation: 0.08,
    radius: 9,
    color: '#a8a6ff',
    shape: 'portal',
    achievement: 'behind_build',
    accent: '#b8ff7a',
    summary: 'Behind-the-build stop retained for future authored story.',
    lines: [
      'Engine room: Three.js visuals, Rapier physics, local resume data, and Supabase-backed counters.',
      'The repository link opens the source behind the drive world.',
    ],
    actions: [{ label: 'Repository', href: 'https://github.com/Abdullah-Mehtab/Abdullah-Mehtab' }],
  },
  {
    id: 'drift',
    name: 'Stunt Yard',
    kind: 'Driving',
    title: 'Stunt Foundation',
    districtId: 'stunt-yard',
    position: [98, 0, -72],
    rotation: -0.48,
    radius: 11,
    color: '#ff9b6d',
    shape: 'rampyard',
    achievement: 'ramp_yard',
    accent: '#ff7a59',
    summary: 'Stunt area foundation replaces the rejected old layout.',
    lines: ['A dedicated driving yard for ramps, boosters, handbrake turns, and clean landings.'],
  },
  {
    id: 'data-pier',
    name: 'Data Pier',
    kind: 'Visitor Trail',
    title: 'Data Pier',
    districtId: 'west-pier',
    position: [-106, 0, 46],
    rotation: 0.68,
    radius: 9,
    color: '#79ffc5',
    shape: 'pier',
    achievement: 'data_pier',
    accent: '#79ffc5',
    summary: 'Small pier foundation keeps the data stop on the coastline.',
    lines: [
      'Signal pier for page views, zone visits, and interaction counts.',
      'Visitor signals are stored as hashed analytics events.',
    ],
  },
  {
    id: 'potato',
    name: 'Potato Farm',
    kind: 'Farm Counter',
    title: 'Potato Patch',
    districtId: 'west-services',
    position: [-62, 0, -116],
    rotation: 0.18,
    radius: 9,
    color: '#c79b56',
    shape: 'farm',
    achievement: 'potato_farm',
    accent: '#d1ff78',
    summary: 'Compatibility stop for the old farm idea without a decoration pass.',
    lines: [
      'Stylized potato counter beside the farm track.',
      'Press P nearby, or use the summon button, to grow one temporary potato and increment the counter.',
    ],
    potatoFarm: true,
  },
];

export const zonePresentation = {
  landing: {
    respawn: { position: [10, 1.08, -56], heading: -0.55 },
    camera: [46, 8, -126],
    target: [30, 2, -104],
    fov: 42,
  },
  education: {
    respawn: { position: [-96, 1.08, 78], heading: -0.68 },
    camera: [-128, 12, 66],
    target: [-104, 5, 82],
    fov: 42,
  },
  security: {
    respawn: { position: [-98, 1.08, -24], heading: -2.11 },
    camera: [-122, 9, -50],
    target: [-98, 3, -42],
    fov: 42,
  },
  projects: {
    respawn: { position: [70, 1.08, 64], heading: 0.36 },
    camera: [96, 9, 92],
    target: [84, 3, 72],
    fov: 42,
  },
  sentinel: {
    respawn: { position: [48, 1.08, 96], heading: 0.55 },
    camera: [18, 16, 136],
    target: [16, 7, 118],
    fov: 42,
  },
  career: {
    respawn: { position: [98, 1.08, -38], heading: 1.4 },
    camera: [125, 10, -22],
    target: [108, 3, -28],
    fov: 42,
  },
  skills: {
    respawn: { position: [-106, 1.08, -92], heading: -2.63 },
    camera: [-118, 10, -92],
    target: [-92, 3, -78],
    fov: 42,
  },
  awards: {
    respawn: { position: [-72, 1.08, 94], heading: 0.94 },
    camera: [-70, 11, 100],
    target: [-54, 4, 86],
    fov: 42,
  },
  cv: {
    respawn: { position: [12, 1.08, -84], heading: 2.94 },
    camera: [22, 9, -98],
    target: [2, 3, -82],
    fov: 42,
  },
  todo: {
    respawn: { position: [-82, 1.08, 16], heading: -2.68 },
    camera: [-108, 9, 26],
    target: [-92, 3, 18],
    fov: 42,
  },
  circuit: {
    respawn: { position: [48, 1.08, 96], heading: 0.42 },
    camera: [56, 10, 118],
    target: [48, 4, 96],
    fov: 42,
  },
  contact: {
    respawn: { position: [120, 1.08, 78], heading: 2.36 },
    camera: [136, 9, 58],
    target: [118, 3, 48],
    fov: 42,
  },
  behind: {
    respawn: { position: [12, 1.08, -84], heading: -2.8 },
    camera: [-44, 10, -118],
    target: [-26, 3, -104],
    fov: 42,
  },
  drift: {
    respawn: { position: [88, 1.08, -72], heading: 0.72 },
    camera: [116, 10, -86],
    target: [98, 3, -72],
    fov: 42,
  },
  'data-pier': {
    respawn: { position: [-132, 1.08, 66], heading: -2.35 },
    camera: [-128, 9, 54],
    target: [-106, 3, 46],
    fov: 42,
  },
  potato: {
    respawn: { position: [-76, 1.08, -122], heading: 2.36 },
    camera: [-82, 9, -128],
    target: [-62, 3, -116],
    fov: 42,
  },
};

export const achievementDefinitions = [
  ['first_stop', 'First Stop', 'Interact with the Start Hub.'],
  ['security_lab', 'Security Pass', 'Open the Security Lab.'],
  ['security_scan', 'Security Scan', 'Complete the scanner gate sequence.'],
  ['projects_foundry', 'Project Heat', 'Open the Projects Foundry.'],
  ['cyber_sentinel', 'Sentinel Signal', 'Visit Cyber Sentinel Tower.'],
  ['career_office', 'Work Log', 'Open the Career Office.'],
  ['skills_terminal', 'Stack Trace', 'Open the Skills Terminal.'],
  ['education_library', 'Academic Archive', 'Open the Education Library.'],
  ['awards_tower', 'Trophy Case', 'Open the Awards Tower.'],
  ['cv_vault', 'Formal Mode', 'Open the CV Vault.'],
  ['todo_board', 'Still Building', 'Open the Todo Board.'],
  ['circuit_gate', 'Track Curious', 'Start the circuit gate.'],
  ['circuit_finish', 'Clean Circuit', 'Finish the island checkpoint circuit.'],
  ['contact_port', 'Signal Sent', 'Open the Contact Port.'],
  ['behind_build', 'Look Under The Hood', 'Open Behind The Build.'],
  ['ramp_yard', 'Ramp Yard', 'Visit the driving yard.'],
  ['data_pier', 'Data Pier', 'Visit the data pier.'],
  ['potato_farm', 'Potato Patch', 'Visit the potato farm.'],
  ['potato_summon', 'Potato Summoner', 'Summon a blocky potato.'],
  ['boost', 'Boosted', 'Use boost while driving.'],
  ['boost_pad', 'Pad Launched', 'Hit a boost pad.'],
  ['jump', 'Suspension Check', 'Jump the car.'],
  ['ramp_jump', 'Clean Air', 'Launch from a ramp.'],
  ['data_shards', 'Signal Collector', 'Collect every floating data shard.'],
  ['distance_1km', 'One Kilometer', 'Drive at least 1 km.'],
  ['all_zones', 'Full Tour', 'Interact with every portfolio zone.'],
];

export const circuitCheckpoints = [
  [48, 0, 96],
  [28, 0, 140],
  [-48, 0, 132],
  [-112, 0, 88],
  [-122, 0, 18],
  [-126, 0, -56],
  [-76, 0, -122],
  [-28, 0, -141],
  [46, 0, -136],
  [99, 0, -85],
  [88, 0, -72],
  [98, 0, -38],
  [131, 0, -28],
  [138, 0, 42],
  [120, 0, 78],
  [91, 0, 101],
  [48, 0, 96],
];
