// ABOUTME: Defines the authored /play world layout, route graph, zones, and gameplay checkpoints.
// ABOUTME: Gate 2R keeps this data foundation-only so later art passes start from clean geometry.

export const WORLD_HALF_SIZE = 190;
export const MAP_PADDING = 24;
export const ISLAND_RADIUS = 158;
export const WATER_RADIUS = ISLAND_RADIUS + 42;
export const SECURITY_SCAN_OFFSET = [18, 14];
export const SECURITY_SCAN_ROTATION = -1.93;

export const roadSurfaceProfiles = {
  avenue: {
    label: 'Main Avenue',
    grip: 1.04,
    drag: 0.985,
    smoke: '#dce7df',
    skid: '#16241f',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  street: {
    label: 'District Street',
    grip: 1.0,
    drag: 0.975,
    smoke: '#d4ddd3',
    skid: '#1f2a24',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  plaza: {
    label: 'Plaza Stone',
    grip: 0.96,
    drag: 0.96,
    smoke: '#ded7c8',
    skid: '#373126',
    audio: 'stone',
    particle: 'stone-chip',
  },
  security: {
    label: 'Security Resin',
    grip: 1.08,
    drag: 0.98,
    smoke: '#9ee8ff',
    skid: '#07394a',
    audio: 'synth-asphalt',
    particle: 'scan-sparks',
  },
  stunt: {
    label: 'Stunt Rubber',
    grip: 1.14,
    drag: 0.97,
    smoke: '#ffd9a8',
    skid: '#42231b',
    audio: 'rubber',
    particle: 'rubber-fleck',
  },
  dirt: {
    label: 'Packed Dirt',
    grip: 0.74,
    drag: 0.9,
    smoke: '#c4a077',
    skid: '#6f4b2e',
    audio: 'dirt',
    particle: 'dust-heavy',
  },
  bridge: {
    label: 'Pier Deck',
    grip: 0.9,
    drag: 0.94,
    smoke: '#c6d4dd',
    skid: '#2d3f47',
    audio: 'wood',
    particle: 'splinter',
  },
};

export const districtFootprints = [
  { id: 'launch-run', label: 'Launch Run', center: [0, -96], size: [38, 28], color: '#7cffb2', kind: 'plaza' },
  { id: 'fcc-campus', label: 'FCC Campus', center: [-86, 74], size: [56, 38], color: '#9ccfff', kind: 'campus' },
  { id: 'security-yard', label: 'Security Yard', center: [-94, -38], size: [42, 32], color: '#68d8ff', kind: 'security' },
  { id: 'gallery-side', label: 'Gallery Side', center: [82, -4], size: [48, 42], color: '#ffcc66', kind: 'workshop' },
  { id: 'north-ridge', label: 'North Ridge', center: [18, 104], size: [60, 30], color: '#ff6d8d', kind: 'tower' },
  { id: 'west-service', label: 'West Service', center: [-72, -86], size: [50, 34], color: '#92ffea', kind: 'trail' },
  { id: 'stunt-cove', label: 'Stunt Cove', center: [64, -68], size: [42, 30], color: '#ff9b6d', kind: 'driving' },
  { id: 'east-harbor', label: 'East Harbor', center: [102, 38], size: [38, 30], color: '#78b7ff', kind: 'harbor' },
  { id: 'data-pier', label: 'Data Pier', center: [-116, 42], size: [26, 24], color: '#79ffc5', kind: 'pier' },
];

export const terrainBrushes = [];
export const meadowDetailPatches = [];
export const districtSurfaceBreakups = [];
export const fieldMotifClusters = [];
export const canalSegments = [];
export const scenicPropZones = [];

export const roadPaths = [
  {
    id: 'coastal-loop',
    label: 'Outer Loop',
    hierarchy: 'avenue',
    closed: true,
    width: 4.4,
    shoulder: 1.05,
    color: '#24342c',
    points: [
      [0, -108],
      [48, -98],
      [92, -62],
      [110, -12],
      [98, 42],
      [62, 88],
      [8, 110],
      [-52, 100],
      [-96, 58],
      [-112, 4],
      [-96, -52],
      [-48, -96],
    ],
  },
  {
    id: 'arrival-spine',
    label: 'Arrival Spine',
    hierarchy: 'plaza',
    width: 4.0,
    shoulder: 0.85,
    color: '#2f3f38',
    points: [
      [0, -108],
      [-12, -76],
      [-28, -46],
      [-48, -18],
      [-70, 18],
      [-96, 58],
    ],
  },
  {
    id: 'campus-entry',
    label: 'Campus Entry',
    hierarchy: 'plaza',
    width: 3.8,
    shoulder: 0.8,
    color: '#303b30',
    points: [
      [-96, 58],
      [-84, 76],
      [-52, 100],
    ],
  },
  {
    id: 'security-spur',
    label: 'Security Spur',
    hierarchy: 'security',
    width: 4.0,
    shoulder: 0.8,
    color: '#163a42',
    points: [
      [-48, -18],
      [-72, -28],
      [-88, -34],
    ],
  },
  {
    id: 'gallery-link',
    label: 'Gallery Link',
    hierarchy: 'street',
    width: 3.8,
    shoulder: 0.75,
    color: '#2d382d',
    points: [
      [-28, -46],
      [8, -34],
      [48, -24],
      [82, -10],
      [110, -12],
    ],
  },
  {
    id: 'stunt-service',
    label: 'Stunt Service',
    hierarchy: 'stunt',
    width: 4.0,
    shoulder: 0.85,
    color: '#3c2722',
    points: [
      [0, -108],
      [24, -86],
      [54, -76],
      [92, -62],
    ],
  },
  {
    id: 'west-service',
    label: 'West Service',
    hierarchy: 'dirt',
    width: 3.6,
    shoulder: 0.8,
    color: '#7a5a37',
    points: [
      [-88, -34],
      [-88, -70],
      [-48, -96],
    ],
  },
  {
    id: 'pier-link',
    label: 'Pier Link',
    hierarchy: 'bridge',
    width: 3.4,
    shoulder: 0.7,
    color: '#32464b',
    points: [
      [-96, 58],
      [-110, 34],
      [-112, 4],
    ],
  },
];

export const routeThresholds = [
  { id: 'launch-entry', label: 'Launch', center: [0, -108], position: [0, 0.05, -108], rotation: 0.25, width: 12, depth: 8, color: '#7cffb2' },
  { id: 'campus-entry', label: 'Campus', center: [-96, 58], position: [-96, 0.05, 58], rotation: -0.82, width: 12, depth: 8, color: '#9ccfff' },
  { id: 'security-entry', label: 'Security', center: [-72, -28], position: [-72, 0.05, -28], rotation: -1.93, width: 12, depth: 8, color: '#68d8ff' },
  { id: 'stunt-entry', label: 'Stunt', center: [54, -76], position: [54, 0.05, -76], rotation: 0.86, width: 12, depth: 8, color: '#ff9b6d' },
];

export const roadSegments = roadPaths.flatMap((path) => pathToSegments(path));

function pathToSegments(path) {
  const segments = [];
  const limit = path.closed ? path.points.length : path.points.length - 1;
  for (let index = 0; index < limit; index += 1) {
    const a = path.points[index];
    const b = path.points[(index + 1) % path.points.length];
    const dx = b[0] - a[0];
    const dz = b[1] - a[1];
    const length = Math.hypot(dx, dz);
    segments.push([
      (a[0] + b[0]) / 2,
      (a[1] + b[1]) / 2,
      path.width,
      length + path.width * 0.64,
      Math.atan2(dx, dz),
    ]);
  }
  return segments;
}

export const boostPads = [
  {
    id: 'scanner-surge',
    label: 'Scanner Surge',
    position: [-88, 0, -34],
    rotation: 2.25,
    impulse: 22,
    lift: 0.1,
    color: '#6ce7ff',
    sound: 'boost-scan',
  },
  {
    id: 'document-dash',
    label: 'Document Dash',
    position: [-24, 0, -96],
    rotation: -1.0,
    impulse: 20,
    lift: 0.12,
    color: '#fff2a8',
    sound: 'boost-paper',
  },
  {
    id: 'stunt-kicker',
    label: 'Stunt Kicker',
    position: [54, 0, -76],
    rotation: 0.2,
    impulse: 24,
    lift: 0.2,
    color: '#ff9b6d',
    sound: 'boost-stunt',
  },
];

export const worldZones = [
  {
    id: 'landing',
    name: 'Launch Plaza',
    kind: 'Home',
    title: 'Launch Run',
    districtId: 'launch-run',
    position: [4, 0, -94],
    rotation: 0.28,
    radius: 9,
    color: '#7cffb2',
    shape: 'hub',
    dialogueId: '0',
    achievement: 'first_stop',
    accent: '#7cffb2',
    summary: 'Start point for the portfolio drive.',
    actions: [
      { label: 'Main Portfolio', href: '../index.html' },
      { label: 'Projects', href: '../projects.html' },
    ],
  },
  {
    id: 'education',
    name: 'FCC Education Grove',
    kind: 'Academics',
    title: 'FCC Education Grove',
    districtId: 'fcc-campus',
    position: [-104, 0, 78],
    rotation: -0.08,
    radius: 11,
    color: '#9ccfff',
    shape: 'library',
    dialogueId: '6',
    achievement: 'education_library',
    accent: '#9ccfff',
    summary: 'Forman Christian College University S-block identity remains protected here.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'security',
    name: 'Security Lab Gate',
    kind: 'Offensive Security',
    title: 'Cyber Sentinel Lab',
    districtId: 'security-yard',
    position: [-106, 0, -48],
    rotation: -0.28,
    radius: 13,
    color: '#68d8ff',
    shape: 'lab',
    dialogueId: '1',
    achievement: 'security_lab',
    scanRequired: true,
    accent: '#68d8ff',
    summary: 'Security portfolio stop with scan interaction compatibility retained.',
    actions: [
      { label: 'CV', href: '../cv.html' },
      { label: 'Cyber Sentinel', href: '../cyber-sentinel.html' },
    ],
  },
  {
    id: 'projects',
    name: 'Projects Yard',
    kind: 'Project Gallery',
    title: 'Project Yard',
    districtId: 'gallery-side',
    position: [78, 0, 6],
    rotation: -0.44,
    radius: 10,
    color: '#ffcc66',
    shape: 'foundry',
    achievement: 'projects_foundry',
    projectGallery: true,
    accent: '#ffcc66',
    summary: 'Project links stay available while the district waits for a later art pass.',
    actions: [{ label: 'Projects Page', href: '../projects.html' }],
  },
  {
    id: 'sentinel',
    name: 'Cyber Sentinel Ridge',
    kind: 'Final Year Project',
    title: 'Cyber Sentinel Ridge',
    districtId: 'north-ridge',
    position: [10, 0, 122],
    rotation: -0.12,
    radius: 11,
    color: '#ff6d8d',
    shape: 'tower',
    dialogueId: '3',
    achievement: 'cyber_sentinel',
    accent: '#ff6d8d',
    summary: 'Future ridge landmark for cybersecurity work.',
    actions: [{ label: 'Read Blog', href: '../cyber-sentinel.html' }],
  },
  {
    id: 'career',
    name: 'Career Signal Office',
    kind: 'Experience',
    title: 'Career Office',
    districtId: 'gallery-side',
    position: [92, 0, -30],
    rotation: -0.24,
    radius: 10,
    color: '#b6a0ff',
    shape: 'office',
    dialogueId: '5',
    achievement: 'career_office',
    accent: '#7df0ff',
    summary: 'Career evidence stop with existing portfolio actions preserved.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'skills',
    name: 'Skills Terminal',
    kind: 'Stack',
    title: 'Skills Service Road',
    districtId: 'west-service',
    position: [-96, 0, -82],
    rotation: 0.24,
    radius: 10,
    color: '#92ffea',
    shape: 'terminal',
    dialogueId: '2',
    achievement: 'skills_terminal',
    accent: '#92ffea',
    summary: 'Technical skills stop on the west service foundation.',
    actions: [{ label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' }],
  },
  {
    id: 'awards',
    name: 'Archive Steps',
    kind: 'Certificates',
    title: 'Awards Archive',
    districtId: 'fcc-campus',
    position: [-62, 0, 80],
    rotation: -0.18,
    radius: 8,
    color: '#ffdf8a',
    shape: 'trophy',
    dialogueId: '7',
    achievement: 'awards_tower',
    accent: '#ffd166',
    summary: 'Awards stop near campus without adding decoration in Gate 2R.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'cv',
    name: 'CV Vault',
    kind: 'Resume',
    title: 'CV Vault',
    districtId: 'launch-run',
    position: [-24, 0, -82],
    rotation: 0.12,
    radius: 9,
    color: '#e6f3ff',
    shape: 'vault',
    achievement: 'cv_vault',
    accent: '#f7f5a8',
    summary: 'CV action remains reachable from the south run.',
    lines: [
      'Resume archive, project record, certificates, skills, awards, and downloadable PDFs.',
      'Open the document-first version for the full professional profile.',
    ],
    actions: [
      { label: 'Open CV Page', href: '../cv.html' },
      { label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' },
      { label: 'Cyber CV PDF', href: '../Abdullah-Mehtab-CV-Cyber-v2.pdf' },
    ],
  },
  {
    id: 'todo',
    name: 'Todo Board',
    kind: 'Blog / List',
    title: 'Todo Board',
    districtId: 'data-pier',
    position: [-123, 0, 20],
    rotation: 0.34,
    radius: 9,
    color: '#d8ff92',
    shape: 'board',
    achievement: 'todo_board',
    accent: '#fca5ff',
    summary: 'Existing todo page action remains compatible.',
    lines: [
      'The never-ending list keeps active tasks, experiments, reminders, and ideas visible.',
      'A lightweight log for work that is being tested, refined, or revisited.',
    ],
    actions: [{ label: 'Open Todo', href: '../todo.html' }],
  },
  {
    id: 'circuit',
    name: 'Circuit Gate',
    kind: 'Time Trial',
    title: 'Circuit Start',
    districtId: 'north-ridge',
    position: [48, 0, 82],
    rotation: -0.28,
    radius: 12,
    color: '#ff9b6d',
    shape: 'gate',
    achievement: 'circuit_gate',
    accent: '#ff9b6d',
    startsCircuit: true,
    summary: 'Circuit foundation stays testable, but final stunt art is deferred.',
    lines: [
      'This gate starts the island loop circuit.',
      'Follow the checkpoints around the outer loop and return clean.',
    ],
  },
  {
    id: 'contact',
    name: 'Signal Harbor',
    kind: 'Links',
    title: 'Signal Harbor',
    districtId: 'east-harbor',
    position: [118, 0, 34],
    rotation: -0.34,
    radius: 9,
    color: '#78b7ff',
    shape: 'post',
    dialogueId: '8',
    achievement: 'contact_port',
    accent: '#78b7ff',
    summary: 'Contact action remains available on the east harbor foundation.',
    actions: [
      { label: 'GitHub', href: 'https://github.com/Abdullah-Mehtab' },
      { label: 'LinkedIn', href: 'https://linkedin.com/in/abdullah-mehtab' },
      { label: 'Email', href: 'mailto:abdullahmehtab666@gmail.com' },
    ],
  },
  {
    id: 'behind',
    name: 'Behind The Build',
    kind: 'Stack',
    title: 'Behind The Build',
    districtId: 'launch-run',
    position: [22, 0, -66],
    rotation: 0.08,
    radius: 9,
    color: '#a8a6ff',
    shape: 'portal',
    achievement: 'behind_build',
    accent: '#b8ff7a',
    summary: 'Behind-the-build stop retained for future authored story.',
    lines: [
      'Engine room: Three.js visuals, Rapier physics, local resume data, and Supabase-backed counters.',
      'The repository link opens the source behind the drive world.',
    ],
    actions: [{ label: 'Repository', href: 'https://github.com/Abdullah-Mehtab/Abdullah-Mehtab' }],
  },
  {
    id: 'drift',
    name: 'Stunt Yard',
    kind: 'Driving',
    title: 'Stunt Foundation',
    districtId: 'stunt-cove',
    position: [72, 0, -88],
    rotation: -0.48,
    radius: 11,
    color: '#ff9b6d',
    shape: 'rampyard',
    achievement: 'ramp_yard',
    accent: '#ff7a59',
    summary: 'Stunt area foundation replaces the rejected old layout.',
    lines: ['A dedicated driving yard for ramps, boosters, handbrake turns, and clean landings.'],
  },
  {
    id: 'data-pier',
    name: 'Data Pier',
    kind: 'Visitor Trail',
    title: 'Data Pier',
    districtId: 'data-pier',
    position: [-130, 0, 50],
    rotation: 0.68,
    radius: 9,
    color: '#79ffc5',
    shape: 'pier',
    achievement: 'data_pier',
    accent: '#79ffc5',
    summary: 'Small pier foundation keeps the data stop on the coastline.',
    lines: [
      'Signal pier for page views, zone visits, and interaction counts.',
      'Visitor signals are stored as hashed analytics events.',
    ],
  },
  {
    id: 'potato',
    name: 'Potato Farm',
    kind: 'Farm Counter',
    title: 'Potato Patch',
    districtId: 'west-service',
    position: [-42, 0, -116],
    rotation: 0.18,
    radius: 9,
    color: '#c79b56',
    shape: 'farm',
    achievement: 'potato_farm',
    accent: '#d1ff78',
    summary: 'Compatibility stop for the old farm idea without a decoration pass.',
    lines: [
      'Stylized potato counter beside the farm track.',
      'Press P nearby, or use the summon button, to grow one temporary potato and increment the counter.',
    ],
    potatoFarm: true,
  },
];

export const zonePresentation = {
  landing: {
    respawn: { position: [-9, 1.08, -84], heading: 0.36 },
    camera: [18, 8, -126],
    target: [4, 2, -94],
    fov: 42,
  },
  education: {
    respawn: { position: [-96, 1.08, 58], heading: 0.72 },
    camera: [-128, 12, 66],
    target: [-104, 5, 78],
    fov: 42,
  },
  security: {
    respawn: { position: [-88, 1.08, -34], heading: -1.93 },
    camera: [-122, 9, -50],
    target: [-106, 3, -48],
    fov: 42,
  },
  projects: {
    respawn: { position: [82, 1.08, -10], heading: 0.36 },
    camera: [96, 9, 30],
    target: [78, 3, 6],
    fov: 42,
  },
  sentinel: {
    respawn: { position: [8, 1.08, 110], heading: -0.05 },
    camera: [18, 16, 136],
    target: [10, 7, 122],
    fov: 42,
  },
  career: {
    respawn: { position: [82, 1.08, -10], heading: 1.4 },
    camera: [114, 10, -20],
    target: [92, 3, -30],
    fov: 42,
  },
  skills: {
    respawn: { position: [-88, 1.08, -70], heading: -2.63 },
    camera: [-116, 10, -92],
    target: [-96, 3, -82],
    fov: 42,
  },
  awards: {
    respawn: { position: [-84, 1.08, 76], heading: 0.94 },
    camera: [-74, 11, 100],
    target: [-62, 4, 80],
    fov: 42,
  },
  cv: {
    respawn: { position: [-24, 1.08, -102], heading: 2.94 },
    camera: [-42, 9, -98],
    target: [-24, 3, -82],
    fov: 42,
  },
  todo: {
    respawn: { position: [-110, 1.08, 34], heading: -2.68 },
    camera: [-138, 9, 24],
    target: [-123, 3, 20],
    fov: 42,
  },
  circuit: {
    respawn: { position: [62, 1.08, 88], heading: 0.42 },
    camera: [64, 10, 112],
    target: [48, 4, 82],
    fov: 42,
  },
  contact: {
    respawn: { position: [98, 1.08, 42], heading: 2.36 },
    camera: [136, 9, 46],
    target: [118, 3, 34],
    fov: 42,
  },
  behind: {
    respawn: { position: [24, 1.08, -86], heading: -2.8 },
    camera: [38, 10, -86],
    target: [22, 3, -66],
    fov: 42,
  },
  drift: {
    respawn: { position: [54, 1.08, -76], heading: 0.72 },
    camera: [92, 10, -98],
    target: [72, 3, -88],
    fov: 42,
  },
  'data-pier': {
    respawn: { position: [-110, 1.08, 34], heading: -2.35 },
    camera: [-148, 9, 54],
    target: [-130, 3, 50],
    fov: 42,
  },
  potato: {
    respawn: { position: [-48, 1.08, -96], heading: 2.36 },
    camera: [-58, 9, -128],
    target: [-42, 3, -116],
    fov: 42,
  },
};

export const achievementDefinitions = [
  ['first_stop', 'First Stop', 'Interact with the Start Hub.'],
  ['security_lab', 'Security Pass', 'Open the Security Lab.'],
  ['security_scan', 'Security Scan', 'Complete the scanner gate sequence.'],
  ['projects_foundry', 'Project Heat', 'Open the Projects Foundry.'],
  ['cyber_sentinel', 'Sentinel Signal', 'Visit Cyber Sentinel Tower.'],
  ['career_office', 'Work Log', 'Open the Career Office.'],
  ['skills_terminal', 'Stack Trace', 'Open the Skills Terminal.'],
  ['education_library', 'Academic Archive', 'Open the Education Library.'],
  ['awards_tower', 'Trophy Case', 'Open the Awards Tower.'],
  ['cv_vault', 'Formal Mode', 'Open the CV Vault.'],
  ['todo_board', 'Still Building', 'Open the Todo Board.'],
  ['circuit_gate', 'Track Curious', 'Start the circuit gate.'],
  ['circuit_finish', 'Clean Circuit', 'Finish the island checkpoint circuit.'],
  ['contact_port', 'Signal Sent', 'Open the Contact Port.'],
  ['behind_build', 'Look Under The Hood', 'Open Behind The Build.'],
  ['ramp_yard', 'Ramp Yard', 'Visit the driving yard.'],
  ['data_pier', 'Data Pier', 'Visit the data pier.'],
  ['potato_farm', 'Potato Patch', 'Visit the potato farm.'],
  ['potato_summon', 'Potato Summoner', 'Summon a blocky potato.'],
  ['boost', 'Boosted', 'Use boost while driving.'],
  ['boost_pad', 'Pad Launched', 'Hit a boost pad.'],
  ['jump', 'Suspension Check', 'Jump the car.'],
  ['ramp_jump', 'Clean Air', 'Launch from a ramp.'],
  ['data_shards', 'Signal Collector', 'Collect every floating data shard.'],
  ['distance_1km', 'One Kilometer', 'Drive at least 1 km.'],
  ['all_zones', 'Full Tour', 'Interact with every portfolio zone.'],
];

export const circuitCheckpoints = [
  [62, 0, 88],
  [8, 0, 110],
  [-52, 0, 100],
  [-96, 0, 58],
  [-112, 0, 4],
  [-96, 0, -52],
  [-48, 0, -96],
  [0, 0, -108],
  [48, 0, -98],
  [92, 0, -62],
  [110, 0, -12],
  [98, 0, 42],
  [62, 0, 88],
];
