// ABOUTME: Defines the authored /play world layout, route graph, zones, and gameplay checkpoints.
// ABOUTME: Gate 2R keeps this data foundation-only so later art passes start from clean geometry.

export const WORLD_HALF_SIZE = 190;
export const MAP_PADDING = 24;
export const ISLAND_RADIUS = 158;
export const WATER_RADIUS = ISLAND_RADIUS + 42;
export const SECURITY_SCAN_OFFSET = [0, 0];
export const SECURITY_SCAN_ROTATION = -2.36;

export const roadSurfaceProfiles = {
  avenue: {
    label: 'Main Avenue',
    grip: 1.04,
    drag: 0.985,
    smoke: '#dce7df',
    skid: '#16241f',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  street: {
    label: 'District Street',
    grip: 1.0,
    drag: 0.975,
    smoke: '#d4ddd3',
    skid: '#1f2a24',
    audio: 'asphalt',
    particle: 'dust-soft',
  },
  plaza: {
    label: 'Plaza Stone',
    grip: 0.96,
    drag: 0.96,
    smoke: '#ded7c8',
    skid: '#373126',
    audio: 'stone',
    particle: 'stone-chip',
  },
  security: {
    label: 'Security Resin',
    grip: 1.08,
    drag: 0.98,
    smoke: '#9ee8ff',
    skid: '#07394a',
    audio: 'synth-asphalt',
    particle: 'scan-sparks',
  },
  dirt: {
    label: 'Packed Dirt',
    grip: 0.74,
    drag: 0.9,
    smoke: '#c4a077',
    skid: '#6f4b2e',
    audio: 'dirt',
    particle: 'dust-heavy',
  },
  bridge: {
    label: 'Pier Deck',
    grip: 0.9,
    drag: 0.94,
    smoke: '#c6d4dd',
    skid: '#2d3f47',
    audio: 'wood',
    particle: 'splinter',
  },
};

export const districtFootprints = [
  { id: 'launch-run', label: 'Launch Run', center: [10, -98], size: [34, 24], color: '#7cffb2', kind: 'plaza' },
  { id: 'fcc-campus', label: 'FCC Campus', center: [-74, 58], size: [48, 34], color: '#9ccfff', kind: 'campus' },
  { id: 'security-yard', label: 'Security Yard', center: [-116, -50], size: [34, 26], color: '#68d8ff', kind: 'security' },
  { id: 'gallery-side', label: 'Gallery Side', center: [96, -16], size: [42, 34], color: '#ffcc66', kind: 'workshop' },
  { id: 'north-ridge', label: 'North Ridge', center: [34, 108], size: [54, 26], color: '#ff6d8d', kind: 'tower' },
  { id: 'west-service', label: 'West Service', center: [-72, -88], size: [42, 28], color: '#92ffea', kind: 'trail' },
  { id: 'east-harbor', label: 'East Harbor', center: [116, 34], size: [34, 26], color: '#78b7ff', kind: 'harbor' },
  { id: 'data-pier', label: 'Data Pier', center: [-128, 38], size: [24, 22], color: '#79ffc5', kind: 'pier' },
];

export const terrainBrushes = [];
export const meadowDetailPatches = [];
export const districtSurfaceBreakups = [];
export const fieldMotifClusters = [];
export const canalSegments = [];
export const scenicPropZones = [];

export const roadPaths = [
  {
    id: 'coastal-loop',
    label: 'Outer Loop',
    hierarchy: 'avenue',
    closed: true,
    width: 4.4,
    shoulder: 1.05,
    color: '#24342c',
    points: [
      [0, -110],
      [56, -100],
      [98, -64],
      [114, -10],
      [104, 46],
      [70, 92],
      [18, 116],
      [-52, 104],
      [-100, 58],
      [-116, -8],
      [-94, -58],
      [-52, -98],
    ],
  },
  {
    id: 'campus-boulevard',
    label: 'Campus Boulevard',
    hierarchy: 'plaza',
    width: 4.0,
    shoulder: 0.85,
    color: '#2f3f38',
    points: [
      [0, -110],
      [-18, -82],
      [-42, -48],
      [-68, -12],
      [-100, 58],
    ],
  },
  {
    id: 'security-spur',
    label: 'Security Spur',
    hierarchy: 'security',
    width: 4.0,
    shoulder: 0.8,
    color: '#163a42',
    points: [
      [-68, -12],
      [-82, -34],
      [-94, -58],
    ],
  },
  {
    id: 'farm-service',
    label: 'Farm Service',
    hierarchy: 'dirt',
    width: 3.6,
    shoulder: 0.8,
    color: '#7a5a37',
    points: [
      [-52, -98],
      [-38, -124],
    ],
  },
  {
    id: 'pier-deck',
    label: 'Pier Deck',
    hierarchy: 'bridge',
    width: 3.4,
    shoulder: 0.7,
    color: '#32464b',
    points: [
      [-100, 58],
      [-128, 50],
    ],
  },
];

export const routeThresholds = [
  { id: 'launch-entry', label: 'Launch', center: [0, -110], position: [0, 0.05, -110], rotation: 0.36, width: 10, depth: 7, color: '#7cffb2' },
  { id: 'campus-entry', label: 'Campus', center: [-100, 58], position: [-100, 0.05, 58], rotation: -0.72, width: 10, depth: 7, color: '#9ccfff' },
  { id: 'security-entry', label: 'Security', center: [-82, -34], position: [-82, 0.05, -34], rotation: -2.56, width: 10, depth: 7, color: '#68d8ff' },
];

export const roadSegments = roadPaths.flatMap((path) => pathToSegments(path));

function pathToSegments(path) {
  const segments = [];
  const limit = path.closed ? path.points.length : path.points.length - 1;
  for (let index = 0; index < limit; index += 1) {
    const a = path.points[index];
    const b = path.points[(index + 1) % path.points.length];
    const dx = b[0] - a[0];
    const dz = b[1] - a[1];
    const length = Math.hypot(dx, dz);
    segments.push([
      (a[0] + b[0]) / 2,
      (a[1] + b[1]) / 2,
      path.width,
      length + path.width * 0.64,
      Math.atan2(dx, dz),
    ]);
  }
  return segments;
}

export const boostPads = [];

export const worldZones = [
  {
    id: 'landing',
    name: 'Launch Plaza',
    kind: 'Home',
    title: 'Launch Run',
    districtId: 'launch-run',
    position: [12, 0, -96],
    rotation: 0.36,
    radius: 9,
    color: '#7cffb2',
    shape: 'hub',
    dialogueId: '0',
    achievement: 'first_stop',
    accent: '#7cffb2',
    summary: 'Start point for the portfolio drive.',
    actions: [
      { label: 'Main Portfolio', href: '../index.html' },
      { label: 'Projects', href: '../projects.html' },
    ],
  },
  {
    id: 'education',
    name: 'FCC Education Grove',
    kind: 'Academics',
    title: 'FCC Education Grove',
    districtId: 'fcc-campus',
    position: [-74, 0, 58],
    rotation: -0.43,
    radius: 11,
    color: '#9ccfff',
    shape: 'library',
    dialogueId: '6',
    achievement: 'education_library',
    accent: '#9ccfff',
    summary: 'Forman Christian College University S-block identity remains protected here.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'security',
    name: 'Security Lab Gate',
    kind: 'Offensive Security',
    title: 'Cyber Sentinel Lab',
    districtId: 'security-yard',
    position: [-116, 0, -50],
    rotation: -2.36,
    radius: 13,
    color: '#68d8ff',
    shape: 'lab',
    dialogueId: '1',
    achievement: 'security_lab',
    scanRequired: true,
    accent: '#68d8ff',
    summary: 'Security portfolio stop with scan interaction compatibility retained.',
    actions: [
      { label: 'CV', href: '../cv.html' },
      { label: 'Cyber Sentinel', href: '../cyber-sentinel.html' },
    ],
  },
  {
    id: 'projects',
    name: 'Projects Yard',
    kind: 'Project Gallery',
    title: 'Project Yard',
    districtId: 'gallery-side',
    position: [76, 0, -28],
    rotation: -0.34,
    radius: 10,
    color: '#ffcc66',
    shape: 'foundry',
    achievement: 'projects_foundry',
    projectGallery: true,
    accent: '#ffcc66',
    summary: 'Project links stay available while the district waits for a later art pass.',
    actions: [{ label: 'Projects Page', href: '../projects.html' }],
  },
  {
    id: 'sentinel',
    name: 'Cyber Sentinel Ridge',
    kind: 'Final Year Project',
    title: 'Cyber Sentinel Ridge',
    districtId: 'north-ridge',
    position: [10, 0, 129],
    rotation: -0.12,
    radius: 11,
    color: '#ff6d8d',
    shape: 'tower',
    dialogueId: '3',
    achievement: 'cyber_sentinel',
    accent: '#ff6d8d',
    summary: 'Future ridge landmark for cybersecurity work.',
    actions: [{ label: 'Read Blog', href: '../cyber-sentinel.html' }],
  },
  {
    id: 'career',
    name: 'Career Signal Office',
    kind: 'Experience',
    title: 'Career Office',
    districtId: 'gallery-side',
    position: [116, 0, -60],
    rotation: -0.24,
    radius: 10,
    color: '#b6a0ff',
    shape: 'office',
    dialogueId: '5',
    achievement: 'career_office',
    accent: '#7df0ff',
    summary: 'Career evidence stop with existing portfolio actions preserved.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'skills',
    name: 'Skills Terminal',
    kind: 'Stack',
    title: 'Skills Service Road',
    districtId: 'west-service',
    position: [-86, 0, -76],
    rotation: 0.24,
    radius: 10,
    color: '#92ffea',
    shape: 'terminal',
    dialogueId: '2',
    achievement: 'skills_terminal',
    accent: '#92ffea',
    summary: 'Technical skills stop on the west service foundation.',
    actions: [{ label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' }],
  },
  {
    id: 'awards',
    name: 'Archive Steps',
    kind: 'Certificates',
    title: 'Awards Archive',
    districtId: 'fcc-campus',
    position: [-58, 0, 116],
    rotation: -0.18,
    radius: 8,
    color: '#ffdf8a',
    shape: 'trophy',
    dialogueId: '7',
    achievement: 'awards_tower',
    accent: '#ffd166',
    summary: 'Awards stop near campus without adding decoration in Gate 2R.',
    actions: [{ label: 'CV', href: '../cv.html' }],
  },
  {
    id: 'cv',
    name: 'CV Vault',
    kind: 'Resume',
    title: 'CV Vault',
    districtId: 'launch-run',
    position: [-36, 0, -96],
    rotation: 0.12,
    radius: 9,
    color: '#e6f3ff',
    shape: 'vault',
    achievement: 'cv_vault',
    accent: '#f7f5a8',
    summary: 'CV action remains reachable from the south run.',
    lines: [
      'Resume archive, project record, certificates, skills, awards, and downloadable PDFs.',
      'Open the document-first version for the full professional profile.',
    ],
    actions: [
      { label: 'Open CV Page', href: '../cv.html' },
      { label: 'Resume PDF', href: '../Abdullah-Mehtab-Resume-v5.pdf' },
      { label: 'Cyber CV PDF', href: '../Abdullah-Mehtab-CV-Cyber-v2.pdf' },
    ],
  },
  {
    id: 'todo',
    name: 'Todo Planning Studio',
    kind: 'Planning',
    title: 'Todo Planning Studio',
    districtId: 'west-service',
    position: [-96, 0, 4],
    rotation: 0.24,
    radius: 9,
    color: '#d8ff92',
    shape: 'board',
    achievement: 'todo_board',
    accent: '#fca5ff',
    summary: 'Existing todo page action remains compatible.',
    lines: [
      'The never-ending list keeps active tasks, experiments, reminders, and ideas visible.',
      'A lightweight log for work that is being tested, refined, or revisited.',
    ],
    actions: [{ label: 'Open Todo', href: '../todo.html' }],
  },
  {
    id: 'circuit',
    name: 'Circuit Gate',
    kind: 'Time Trial',
    title: 'Circuit Start',
    districtId: 'north-ridge',
    position: [58, 0, 76],
    rotation: -0.28,
    radius: 12,
    color: '#ff9b6d',
    shape: 'gate',
    achievement: 'circuit_gate',
    accent: '#ff9b6d',
    startsCircuit: true,
    summary: 'Circuit foundation stays testable, but final stunt art is deferred.',
    lines: [
      'This gate starts the island loop circuit.',
      'Follow the checkpoints around the outer loop and return clean.',
    ],
  },
  {
    id: 'contact',
    name: 'Signal Harbor',
    kind: 'Links',
    title: 'Signal Harbor',
    districtId: 'east-harbor',
    position: [127, 0, 13],
    rotation: -0.34,
    radius: 9,
    color: '#78b7ff',
    shape: 'post',
    dialogueId: '8',
    achievement: 'contact_port',
    accent: '#78b7ff',
    summary: 'Contact action remains available on the east harbor foundation.',
    actions: [
      { label: 'GitHub', href: 'https://github.com/Abdullah-Mehtab' },
      { label: 'LinkedIn', href: 'https://linkedin.com/in/abdullah-mehtab' },
      { label: 'Email', href: 'mailto:abdullahmehtab666@gmail.com' },
    ],
  },
  {
    id: 'behind',
    name: 'Behind The Build',
    kind: 'Stack',
    title: 'Behind The Build',
    districtId: 'launch-run',
    position: [35, 0, -76],
    rotation: 0.08,
    radius: 9,
    color: '#a8a6ff',
    shape: 'portal',
    achievement: 'behind_build',
    accent: '#b8ff7a',
    summary: 'Behind-the-build stop retained for future authored story.',
    lines: [
      'Engine room: Three.js visuals, Rapier physics, local resume data, and Supabase-backed counters.',
      'The repository link opens the source behind the drive world.',
    ],
    actions: [{ label: 'Repository', href: 'https://github.com/Abdullah-Mehtab/Abdullah-Mehtab' }],
  },
  {
    id: 'data-pier',
    name: 'Data Pier',
    kind: 'Visitor Trail',
    title: 'Data Pier',
    districtId: 'data-pier',
    position: [-136, 0, 50],
    rotation: 0.68,
    radius: 9,
    color: '#79ffc5',
    shape: 'pier',
    achievement: 'data_pier',
    accent: '#79ffc5',
    summary: 'Compatibility data stop; the rejected physical pier object is removed.',
    lines: [
      'Signal pier for page views, zone visits, and interaction counts.',
      'Visitor signals are stored as hashed analytics events.',
    ],
  },
  {
    id: 'potato',
    name: 'Potato Farm',
    kind: 'Farm Counter',
    title: 'Potato Patch',
    districtId: 'west-service',
    position: [-14, 0, -132],
    rotation: 0.18,
    radius: 9,
    color: '#c79b56',
    shape: 'farm',
    achievement: 'potato_farm',
    accent: '#d1ff78',
    summary: 'Compatibility stop for the old farm idea without a decoration pass.',
    lines: [
      'Stylized potato counter beside the farm track.',
      'Press P nearby, or use the summon button, to grow one temporary potato and increment the counter.',
    ],
    potatoFarm: true,
  },
];

export const zonePresentation = {
  landing: {
    respawn: { position: [0, 1.08, -110], heading: 0.36 },
    camera: [24, 8, -136],
    target: [12, 2, -96],
    fov: 42,
  },
  education: {
    respawn: { position: [-96, 1.08, 62], heading: 0.72 },
    camera: [-112, 15, 42],
    target: [-74, 5, 58],
    fov: 42,
  },
  security: {
    respawn: { position: [-94, 1.08, -58], heading: -2.63 },
    camera: [-146, 14, -35],
    target: [-119, 4, -54],
    fov: 44,
  },
  projects: {
    respawn: { position: [114, 1.08, -10], heading: 0.36 },
    camera: [104, 10, 8],
    target: [76, 3, -28],
    fov: 42,
  },
  sentinel: {
    respawn: { position: [18, 1.08, 116], heading: -0.05 },
    camera: [42, 18, 154],
    target: [10, 5, 129],
    fov: 42,
  },
  career: {
    respawn: { position: [114, 1.08, -10], heading: 1.4 },
    camera: [134, 12, -82],
    target: [116, 4, -60],
    fov: 42,
  },
  skills: {
    respawn: { position: [-94, 1.08, -58], heading: -2.63 },
    camera: [-126, 12, -114],
    target: [-94, 4, -84],
    fov: 42,
  },
  awards: {
    respawn: { position: [-52, 1.08, 104], heading: 0.94 },
    camera: [-76, 11, 94],
    target: [-58, 4, 116],
    fov: 42,
  },
  cv: {
    respawn: { position: [-52, 1.08, -98], heading: 2.94 },
    camera: [-58, 13, -116],
    target: [-36, 4, -90],
    fov: 42,
  },
  todo: {
    respawn: { position: [-111.2, 1.08, 11.7], heading: 0.24 },
    camera: [-126, 13, 24],
    target: [-96, 4, 4],
    fov: 42,
  },
  circuit: {
    respawn: { position: [70, 1.08, 92], heading: 0.42 },
    camera: [80, 11, 52],
    target: [58, 4, 76],
    fov: 42,
  },
  contact: {
    respawn: { position: [104, 1.08, 46], heading: 2.36 },
    camera: [99, 11, -10],
    target: [127, 4, 13],
    fov: 42,
  },
  behind: {
    respawn: { position: [0, 1.08, -110], heading: -2.8 },
    camera: [62, 12, -108],
    target: [35, 4, -76],
    fov: 42,
  },
  'data-pier': {
    respawn: { position: [-128, 1.08, 50], heading: -2.35 },
    camera: [-152, 9, 62],
    target: [-136, 3, 50],
    fov: 42,
  },
  potato: {
    respawn: { position: [-38, 1.08, -124], heading: 2.36 },
    camera: [-34, 9, -150],
    target: [-14, 3, -132],
    fov: 42,
  },
};

export const achievementDefinitions = [
  ['first_stop', 'First Stop', 'Interact with the Start Hub.'],
  ['security_lab', 'Security Pass', 'Open the Security Lab.'],
  ['security_scan', 'Security Scan', 'Complete the scanner gate sequence.'],
  ['projects_foundry', 'Project Heat', 'Open the Projects Foundry.'],
  ['cyber_sentinel', 'Sentinel Signal', 'Visit Cyber Sentinel Tower.'],
  ['career_office', 'Work Log', 'Open the Career Office.'],
  ['skills_terminal', 'Stack Trace', 'Open the Skills Terminal.'],
  ['education_library', 'Academic Archive', 'Open the Education Library.'],
  ['awards_tower', 'Trophy Case', 'Open the Awards Tower.'],
  ['cv_vault', 'Formal Mode', 'Open the CV Vault.'],
  ['todo_board', 'Still Building', 'Open the Todo Board.'],
  ['circuit_gate', 'Track Curious', 'Start the circuit gate.'],
  ['circuit_finish', 'Clean Circuit', 'Finish the island checkpoint circuit.'],
  ['contact_port', 'Signal Sent', 'Open the Contact Port.'],
  ['behind_build', 'Look Under The Hood', 'Open Behind The Build.'],
  ['data_pier', 'Data Pier', 'Visit the data pier.'],
  ['potato_farm', 'Potato Patch', 'Visit the potato farm.'],
  ['potato_summon', 'Potato Summoner', 'Summon a blocky potato.'],
  ['boost', 'Boosted', 'Use boost while driving.'],
  ['boost_pad', 'Pad Launched', 'Hit a boost pad.'],
  ['jump', 'Suspension Check', 'Jump the car.'],
  ['ramp_jump', 'Clean Air', 'Launch from a ramp.'],
  ['data_shards', 'Signal Collector', 'Collect every floating data shard.'],
  ['distance_1km', 'One Kilometer', 'Drive at least 1 km.'],
  ['all_zones', 'Full Tour', 'Interact with every portfolio zone.'],
];

export const circuitCheckpoints = [
  [70, 0, 92],
  [18, 0, 116],
  [-52, 0, 104],
  [-100, 0, 58],
  [-116, 0, -8],
  [-94, 0, -58],
  [-52, 0, -98],
  [0, 0, -110],
  [56, 0, -100],
  [98, 0, -64],
  [114, 0, -10],
  [104, 0, 46],
  [70, 0, 92],
];
